### PR TITLE
Fix #691 Add eslint-plugin-vue-scoped-css to `hardcore/vue`

### LINKED ISSUE #691: Add eslint-plugin-vue-scoped-css to `hardcore/vue`
https://github.com/future-architect/eslint-plugin-vue-scoped-css

### PR DESCRIPTION
**Pull request by EvgenyOrekhov**
- Add [eslint-plugin-vue-scoped-css](https://github.com/future-architect/eslint-plugin-vue-scoped-css)
- Allow `<style scoped>` and `<style module>`, forbid plain `<style>`
- Enable all rules

Fix #691

### CODE REVIEW

**Comment by EvgenyOrekhov** [comment]
@alexkramer98 Please take a look at this PR and let me know what you think!

**Comment by alexkramer98** [comment]
Looks good at first sight! I will test this in a project next Tuesday.

**Comment by alexkramer98** [comment]
Tested this in a project and looks good! It doesn't have much css though (Tailwind). I currently don't have a project laying around with more css.
I have never used `::v-` selectors before so I cannot say much about those rules.

I've looked through the docs of all enabled rules and they look sensible.

**Comment by EvgenyOrekhov** [comment]
@alexkramer98 

> I have never used `::v-` selectors before so I cannot say much about those rules.

`::v-deep()`, `::v-global()`, and `::v-slotted()` were deprecated.
The official Vue.js documentation recommends using [`:deep()`](https://vuejs.org/api/sfc-css-features.html#deep-selectors), [`:global()`](https://vuejs.org/api/sfc-css-features.html#global-selectors), and [`:slotted()`](https://vuejs.org/api/sfc-css-features.html#slotted-selectors).
The new pseudo-classes will be enforced by [`v-deep-pseudo-style`](https://future-architect.github.io/eslint-plugin-vue-scoped-css/rules/v-deep-pseudo-style.html), [`v-global-pseudo-style`](https://future-architect.github.io/eslint-plugin-vue-scoped-css/rules/v-global-pseudo-style.html), and [`v-slotted-pseudo-style`](https://future-architect.github.io/eslint-plugin-vue-scoped-css/rules/v-slotted-pseudo-style.html) rules.

**Comment by alexkramer98** [comment]
@EvgenyOrekhov that's pretty cool actually!

**Pull request merged**
